
site_name: CyVerse Austria Documentation
site_url: https://cyverse-austria.github.io/docs
site_description: CyVerse Austria Documentation
site_author: 'Mojib Wali'

# uncomment to show the github icon in the header with
# number of forks & stars
# repo_url: https://github.com/cyverse-austria/docs
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2020-2022 Graz University of Technology'

# logos
medunilogo: 'images/logo-meduni-graz.png'
unigrazlogo: 'images/universitaet_graz_logo_signet.png'
tugrazlogo: 'images/TUG.png'

imgwidth: 70px;
theme:
  highlightjs: true
  features:
    - navigation.tabs
  name: material
  # custom_dir: 'overrides'
  palette:
    primary: 'white'
  font:
    text: 'Open Sans'
    code: 'Roboto Mono'
  logo: 'images/cyverse.png'
  favicon: 'images/favicon.ico'


nav:
  - Home: 'index.md'
  # - Development:
  #   - overview: 'development/index.md'
  - Kubernetes:
    - Services: 'services/kubernetes/index.md'
    - Namespaces: 'services/kubernetes/ns.md'
  - Deployments:
    - Kubernetes: 'deployments/kubernetes-deploy.md'
  - Databases:
    - Databases: 'database/main.md'
    - DE Database: 'database/de-db.md'
    - Metadata Database: 'database/metadata-db.md'
    - Keycloak Database: 'database/keycloak-db.md'
    - Notifications Database: 'database/notifications-db.md'
    - Unleash Database: 'database/unleash-db.md'
    - Grouper Database: 'database/grouper-db.md'
    - QMS Database: 'database/qms-db.md'
    - Portal Database: 'database/portal-db.md'




# Customization
extra:
  generator: false
  social:
  - icon: fontawesome/brands/github-alt
    link: 'https://github.com/cyverse-austria/docs'
extra_css:
  - stylesheets/custom.css

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
